apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
  labels:
    app: postgres
type: Opaque
data:
    pgadmin-password: c3VwZXJzZWNyZXRwYXNzd29yZAo=
    # supersecretpassword
    pgadmin-email: b21lZ2FuaW5lQGdtYWlsLmNvbQo=
    # omeganine@gmail.com