apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "omeganine@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "strongpassword"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        volumeMounts:
         - name: pgadmin-config
           mountPath: /pgadmin4/
           subPath: servers.json
           readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - name: pgadmin-port
    port: 80
    targetPort: 80
    nodePort: 30080
